#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2019 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared device drivers.
#

obj-y			+= irdactl.o

irdactl-objs		:= irda_ctl.o
