#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2016 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared device drivers.
#

obj-y			+= irdasd.o

irdasd-objs		:= irda_sd.o
