/*
 * memory_map_kyocera.h
 *
 *  Created on: Jun 14, 2017
 *      Author: AKKumar
 */

#ifndef APP_SHUBANDROID_INC_MEMORY_MAP_KYOCERA_H_
#define APP_SHUBANDROID_INC_MEMORY_MAP_KYOCERA_H_


/* Sensorhub memory map address */
#define SENSORHUB_MEMORYMAP_BASE_ADDR			(0x20078000)

/* SECTION 1: SENSOR DATA FOR M4 FUSION */
#define M4_FUSION_SENSOR_DATA_SECTION_ADDR			(SENSORHUB_MEMORYMAP_BASE_ADDR)

#define M4FUSION_DATA_BUF_START_ADDR   				(M4_FUSION_SENSOR_DATA_SECTION_ADDR)
#define M4FUSION_DATA_BUF_SIZE						(224)
#define M4FUSION_DATA_PKT_SIZE          			(28)
#define M4FUSION_DATA_BUF_END_ADDR   				(M4FUSION_DATA_BUF_START_ADDR + M4FUSION_DATA_BUF_SIZE)

#define M4_FUSION_SENSOR_DATA_SECTION_SIZE			M4FUSION_DATA_BUF_SIZE


/* SECTION 2: ANDROID BATCH BUFFER */
#define ANDROID_BATCH_BUFFER_SECTION_ADDR           (M4_FUSION_SENSOR_DATA_SECTION_ADDR + M4_FUSION_SENSOR_DATA_SECTION_SIZE)

#define ANDROID_BATCH_BUFFER_SECTION_ADDR_M4        (ANDROID_BATCH_BUFFER_SECTION_ADDR)
#define ANDROID_BATCH_BUFFER_SECTION_SIZE_M4        (14112)
#define ANDROID_BATCH_BUFFER_SECTION_BLANK_M4       (2052)

#define ANDROID_BATCH_BUFFER_SECTION_ADDR_FFE       (ANDROID_BATCH_BUFFER_SECTION_ADDR_M4 + ANDROID_BATCH_BUFFER_SECTION_SIZE_M4 + ANDROID_BATCH_BUFFER_SECTION_BLANK_M4)
#define ANDROID_BATCH_BUFFER_SECTION_SIZE_FFE       (4032)
#define ANDROID_BATCH_BUFFER_SECTION_BLANK_FFE      (516)

#define ANDROID_BATCH_BUFFER_SECTION_SIZE           (ANDROID_BATCH_BUFFER_SECTION_SIZE_M4 + ANDROID_BATCH_BUFFER_SECTION_BLANK_M4 + ANDROID_BATCH_BUFFER_SECTION_SIZE_FFE + ANDROID_BATCH_BUFFER_SECTION_BLANK_FFE)


/* SECTION 3: M4 APP BATCH BUFFER */
#define M4_BATCH_BUFFER_SECTION_ADDR				(ANDROID_BATCH_BUFFER_SECTION_ADDR + ANDROID_BATCH_BUFFER_SECTION_SIZE)

#define M4_BATCH_BUFFER_DATA_ADDR					(M4_BATCH_BUFFER_SECTION_ADDR)
#define M4_BATCH_BUFFER_DATA_SIZE					(256)
#define M4_BATCH_PKT_SIZE					        (32)

#define M4_BATCH_BUFFER_SECTION_SIZE				(M4_BATCH_BUFFER_DATA_SIZE)

/* SECTION 4: EVENT BUFFER */
#define EVENT_BATCH_BUFFER_SECTION_ADDR           	(M4_BATCH_BUFFER_SECTION_ADDR + M4_BATCH_BUFFER_SECTION_SIZE)

#define EVENT_BATCH_BUFFER_DATA_ADDR           		(EVENT_BATCH_BUFFER_SECTION_ADDR)
#define EVENT_BATCH_BUFFER_DATA_SIZE           		(1520)
#define EVENT_BATCH_BUFFER_DATA_BLANK          		(16)

#define EVENT_BATCH_BUFFER_SECTION_SIZE           	(EVENT_BATCH_BUFFER_DATA_SIZE + EVENT_BATCH_BUFFER_DATA_BLANK)

#define SENSORHUB_LAST_USED_ADDR                    (EVENT_BATCH_BUFFER_SECTION_ADDR + EVENT_BATCH_BUFFER_SECTION_SIZE)

/************************************************************************************************************/
/* To fix the address of these sections the addresses are moved to the last section of the memory           */
/* so that it doesnt get changed inspite of change in the model file/ audio buffer/ batch and event buffers */
/************************************************************************************************************/

/* SECTION (5): LIGHTWEIGHT UART */
#define LIGHT_WEIGHT_UART_SECTION_ADDR           		(0x2007E000)

#define LIGHT_WEIGHT_UART_BUF_ADDR						(LIGHT_WEIGHT_UART_SECTION_ADDR)
#define LIGHT_WEIGHT_UART_BUF_SIZE						(4096)

#define LIGHT_WEIGHT_UART_SECTION_SIZE           		(LIGHT_WEIGHT_UART_BUF_SIZE)

/* SECTION 6: COMMAND AND RESPONSE */
#define AP_COMM_COMMAND_RESPONSE_SECTION_ADDR			(0x2007F000)

#define AP_COMM_COMMAND_SIZE							4
#define AP_COMM_PARAMS_SIZE								64
#define AP_COMM_RESULT_SIZE								8
#define AP_COMM_RESPONSE_SIZE							128

#define AP_COMM_COMMAND_ADDR							(AP_COMM_COMMAND_RESPONSE_SECTION_ADDR)
#define AP_COMM_PARAMS_ADDR								(AP_COMM_COMMAND_ADDR + AP_COMM_COMMAND_SIZE)
#define AP_COMM_RESULT_ADDR								(AP_COMM_PARAMS_ADDR + AP_COMM_PARAMS_SIZE)
#define AP_COMM_RESPONSE_ADDR							(AP_COMM_RESULT_ADDR + AP_COMM_RESULT_SIZE)

#define AP_COMM_COMMAND_RESPONSE_SECTION_SIZE			(256)


/* SECTION 7: ANDROID SENSOR DATA */
#define ANDROID_SENSOR_DATA_SECTION_ADDR									(AP_COMM_COMMAND_RESPONSE_SECTION_ADDR + AP_COMM_COMMAND_RESPONSE_SECTION_SIZE)

#define ANDROID_SENSOR_DATA_ADDR											(ANDROID_SENSOR_DATA_SECTION_ADDR)
#define ANDROID_SENSOR_DATA_ACCEL_ADDR										(ANDROID_SENSOR_DATA_ADDR + 0x00)
#define ANDROID_SENSOR_DATA_MAG_ADDR										(ANDROID_SENSOR_DATA_ADDR + 0x08)
#define ANDROID_SENSOR_DATA_GYRO_ADDR										(ANDROID_SENSOR_DATA_ADDR + 0x10)
#define ANDROID_SENSOR_DATA_BARO_ADDR										(ANDROID_SENSOR_DATA_ADDR + 0x18)

#define ANDROID_SENSOR_DATA_ORIENTATION_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x20)
#define ANDROID_SENSOR_DATA_GRAVITY_ADDR									(ANDROID_SENSOR_DATA_ADDR + 0x28)
#define ANDROID_SENSOR_DATA_LINEAR_ACCEL_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x30)
#define ANDROID_SENSOR_DATA_ROTATION_VECTOR_ADDR							(ANDROID_SENSOR_DATA_ADDR + 0x38)
#define ANDROID_SENSOR_DATA_GEO_ROTATION_VECTOR_ADDR						(ANDROID_SENSOR_DATA_ADDR + 0x40)
#define ANDROID_SENSOR_DATA_GAME_ROTATION_VECTOR_ADDR						(ANDROID_SENSOR_DATA_ADDR + 0x48)

#define ANDROID_SENSOR_DATA_MAG_UNCAL_RAW_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x50)
#define ANDROID_SENSOR_DATA_MAG_UNCAL_OFFS_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x58)
#define ANDROID_SENSOR_DATA_GYRO_UNCAL_RAW_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x60)
#define ANDROID_SENSOR_DATA_GYRO_UNCAL_OFFS_ADDR							(ANDROID_SENSOR_DATA_ADDR + 0x68)
#define ANDROID_SENSOR_DATA_ACCEL_UNCAL_RAW_ADDR							(ANDROID_SENSOR_DATA_ADDR + 0x70)
#define ANDROID_SENSOR_DATA_ACCEL_UNCAL_OFFS_ADDR							(ANDROID_SENSOR_DATA_ADDR + 0x78)

#define ANDROID_SENSOR_DATA_STEPCOUNTER_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x80)
#define ANDROID_SENSOR_DATA_AMBIENT_TEMP_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x88)
#define ANDROID_SENSOR_DATA_REL_HUMIDITY_ADDR								(ANDROID_SENSOR_DATA_ADDR + 0x90)

#define ANDROID_SENSOR_DATA_BARO2_ADDR								        (ANDROID_SENSOR_DATA_ADDR + 0x98)

#define ANDROID_SENSOR_DATA_SECTION_SIZE									(256)


/* SECTION 8: CRC32 (new) AREA */
#define CRC32_SECTION_ADDR								(ANDROID_SENSOR_DATA_SECTION_ADDR + ANDROID_SENSOR_DATA_SECTION_SIZE)

#define CRC32_MAX_NUM_SECTIONS							(10)
#define CRC32_SECTION_INFO_BYTES						(4 * 3)	// START,SIZE,CRC32
#define CRC32_X_SECTION_SIZE							(8 + (CRC32_MAX_NUM_SECTIONS * CRC32_SECTION_INFO_BYTES))
#define CRC32_M4_SECTION_ADDR							(CRC32_SECTION_ADDR)
#define CRC32_M4_SECTION_SIZE							(CRC32_X_SECTION_SIZE)
#define CRC32_FFE_SECTION_ADDR							(CRC32_M4_SECTION_ADDR + CRC32_M4_SECTION_SIZE)
#define CRC32_FFE_SECTION_SIZE							(CRC32_X_SECTION_SIZE)

#define CRC32_SECTION_SIZE								(CRC32_M4_SECTION_SIZE + CRC32_FFE_SECTION_SIZE)

/* SECTION 9: M4 RESET LOG */
#define M4_RESET_LOG_INFO_ADDR						(CRC32_SECTION_ADDR + CRC32_SECTION_SIZE)
#define M4_RESET_LOG_INFO_SIZE						(512)

/* SECTION 10: BATCH BUFFER and EVENT BUFFER ADRESS */
#define BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS   (M4_RESET_LOG_INFO_ADDR + M4_RESET_LOG_INFO_SIZE)

#define ANDROID_BATCH_BUFFER_START_ADDR_M4_STORE    (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS)
#define ANDROID_BATCH_BUFFER_END_ADDR_M4_STORE      (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + 4)

#define ANDROID_BATCH_BUFFER_START_ADDR_FFE_STORE   (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + 8)
#define ANDROID_BATCH_BUFFER_END_ADDR_FFE_STORE     (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + 12)

#define EVENT_BATCH_BUFFER_DATA_START_ADDR_STORE    (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + 16)
#define EVENT_BATCH_BUFFER_DATA_END_ADDR_STORE      (BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + 20)

/* for future use so that it doesnt disturb the other block address when this block is changed / added */
#define RESERVE_BATCH_EVENT_BUFFER_SECTION_SIZE     (256)

/* SECTION 11: AUDIO BUFFER INFO*/

#define AUDIO_BUFFER_SECTION_ADDR 					(BATCH_BUFFER_EVENT_BUFFER_SECTION_ADDRESS + RESERVE_BATCH_EVENT_BUFFER_SECTION_SIZE)

#define AUDIO_BUFFER_DMA_START_ADDR					(AUDIO_BUFFER_SECTION_ADDR)
#define AUDIO_BUFFER_DMA_END_ADDR					(AUDIO_BUFFER_DMA_START_ADDR + 4)
#define AUDIO_BUFFER_DMA_READ_ADDR					(AUDIO_BUFFER_DMA_END_ADDR + 4)
#define AUDIO_BUFFER_DMA_READ_VB					(AUDIO_BUFFER_DMA_READ_ADDR + 4)

#define AUDIO_BUFFER_SECTION_SIZE					(AUDIO_BUFFER_DMA_READ_VB - AUDIO_BUFFER_SECTION_ADDR)


/* SECTION 12: RESERVED AREA */
#define RESERVED_AREA_SECTION_ADDR           			(AUDIO_BUFFER_SECTION_ADDR + AUDIO_BUFFER_SECTION_SIZE)

#define RESERVED_AREA_SECTION_SIZE           			(0x2007FFFF - RESERVED_AREA_SECTION_ADDR)

#endif /* APP_SHUBANDROID_INC_MEMORY_MAP_KYOCERA_H_ */
