#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2014 KYOCERA Corporation
# (C) 2015 KYOCERA Corporation
#
# Makefile for misc object
#
obj-$(CONFIG_SECURITY_KCPDSM) += kcpdsm.o
